---
- name: install ssh moduli
  ## fixes openssh warning "could not open /opt/etc/ssh/moduli, using fixed modulus"
  ## see:
  ## https://security.stackexchange.com/questions/79043/is-it-considered-worth-it-to-replace-opensshs-moduli-file
  ## https://www.linode.com/docs/security/advanced-ssh-server-security/
  ## https://github.com/openssh/openssh-portable/blob/master/moduli
  copy:
    ## downloaded on 2020-04-22 from:
    ## https://raw.githubusercontent.com/openssh/openssh-portable/master/moduli
    src: ssh-moduli
    dest: /opt/etc/ssh/moduli
    force: true
    mode: 0644
  notify: restart wrt service ssh

- name: tweak ssh server settings
  lineinfile:
    path: /opt/etc/ssh/sshd_config
    regexp: '^#*\s*{{ item.0 }}\b'
    line: '{{ item.0 }} {{ item.1 }}'
    insertbefore: '^Match|^Subsystem'
    firstmatch: true
  loop: "{{ wrt_ssh_settings |dictsort }}"
  loop_control:
    label: "{{ item.0 }}"
  notify: restart wrt service ssh

- name: authorize ssh keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('pipe', keygen_cmd) }}"
    comment: "{{ item |basename |regex_replace('[.]key$') }}"
  vars:
    # use '&&' in the pipe to fail on chmod errors
    keygen_cmd: 'chmod 600 "{{ item }}" && ssh-keygen -y -f "{{ item }}"'
  loop: "{{ wrt_ssh_authorized_keys }}"
  loop_control:
    label: "{{ item | basename }}"
...
