---
- name: activate swap file on every boot
  template:
    src: swapon.init.sh
    dest: /opt/etc/init.d/S99swapon
    mode: 0755

- name: setup and activate swap file
  command: /opt/etc/init.d/S99swapon start
  args:
    creates: "{{ wrt_swap_file }}"
...
